print("Hello my friend")
print("Why we are doing coding in this era of Ai")
print("*")
print("**")
print("***")
print("****")
print("*****")
print("******")
print("*******")
print(2**3**3)
print(2**27)